### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by mx202** [pouriap/FlashGot-For-DownloadGrab#1]
Sorry, But I did not understand this project

Are you modifying the FlashGot add-on to be compatible with Firefox again?

**Comment by pouriap** [comment]
Yes and no.

The FlashGot addon had a program called FlashGot.exe inside it that was responsible for communicating with download managers. This repository is based on the latest update of FlashGot.exe and has added updates to it to make it compatible with newer versions of download managers, and also has added support for new download managers that were previously unsupported.

There's also an addon that I'm writing in hopes of recreating FlashGot's functionality in FF Quantum. It's called Downoad Grab and this program is used by it. You can find it in my other repository: https://github.com/pouriap/Firefox-DownloadGrab

You can download the alpha version in the [latest release](https://github.com/pouriap/Firefox-DownloadGrab/releases/latest).

btw how did you find this repository if I may ask?
Also sorry for the inconvenience, I will add a readme soon.

**Comment by mx202** [comment]
Hello

I tried the extension and the native host on windows 10 and it was working properly so far.
I am happy with this project.

But can you provide a native host for Ubuntu Linux with the ability to specify the path of the program I want to use in the settings

Like the following pictures
![Screenshot from 2020-06-22 17-43-11](https://user-images.githubusercontent.com/66641103/85301682-ccb6d780-b4b0-11ea-8d53-e5e7253da518.png)


* I was looking for a way to run FlashGot on Firefox and didn't find it, and I was looking for a native client patch to link the browser extension with IDM and found this one:
https://github.com/Emano-Waldeck/native-client
But it did not work

Please help

Thank you

**Comment by pouriap** [comment]
Unfortunately this only works on Windows currently. This project is still a work in progress. Once I complete the Windows part I will start working on Linux. But until then you will have to wait. Sorry.

I can't give you an exact time when Linux support will be added because there is still so much to do and I'm not sure how much free time I'm going to have to work on this. But you can keep checking this project regularly to find out when Linux support is added.

**Comment by mx202** [comment]
It's Ok
You did a great work on Windows version
And I'll check your page frequently to see your progress.

Hope to see you working on the linux version soon and realizing my wish.

Thanks a lot

**Comment by pouriap** [comment]
This feature was added in version 0.62.12
